/* Automatically generated by tree-sitter v0.25.3 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 24
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 15
#define ALIAS_COUNT 0
#define TOKEN_COUNT 8
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LF = 1,
  anon_sym_LF_LF = 2,
  anon_sym_COLON = 3,
  sym_field_name = 4,
  aux_sym_field_value_token1 = 5,
  aux_sym_field_value_token2 = 6,
  sym_comment = 7,
  sym_source_file = 8,
  sym_stanza = 9,
  sym_field = 10,
  sym_field_value = 11,
  aux_sym_source_file_repeat1 = 12,
  aux_sym_stanza_repeat1 = 13,
  aux_sym_field_value_repeat1 = 14,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LF] = "\n",
  [anon_sym_LF_LF] = "\n\n",
  [anon_sym_COLON] = ":",
  [sym_field_name] = "field_name",
  [aux_sym_field_value_token1] = "field_value_token1",
  [aux_sym_field_value_token2] = "field_value_token2",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym_stanza] = "stanza",
  [sym_field] = "field",
  [sym_field_value] = "field_value",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_stanza_repeat1] = "stanza_repeat1",
  [aux_sym_field_value_repeat1] = "field_value_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LF] = anon_sym_LF,
  [anon_sym_LF_LF] = anon_sym_LF_LF,
  [anon_sym_COLON] = anon_sym_COLON,
  [sym_field_name] = sym_field_name,
  [aux_sym_field_value_token1] = aux_sym_field_value_token1,
  [aux_sym_field_value_token2] = aux_sym_field_value_token2,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym_stanza] = sym_stanza,
  [sym_field] = sym_field,
  [sym_field_value] = sym_field_value,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_stanza_repeat1] = aux_sym_stanza_repeat1,
  [aux_sym_field_value_repeat1] = aux_sym_field_value_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LF_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_field_name] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_field_value_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_field_value_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_stanza] = {
    .visible = true,
    .named = true,
  },
  [sym_field] = {
    .visible = true,
    .named = true,
  },
  [sym_field_value] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_stanza_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_field_value_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(5);
      if (lookahead == '\n') ADVANCE(7);
      if (lookahead == '#') ADVANCE(13);
      if (lookahead == ':') ADVANCE(9);
      if (('!' <= lookahead && lookahead <= ',') ||
          ('.' <= lookahead && lookahead <= '~')) ADVANCE(10);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(6);
      if (lookahead == '#') ADVANCE(13);
      if (('!' <= lookahead && lookahead <= ',') ||
          ('.' <= lookahead && lookahead <= '9') ||
          (';' <= lookahead && lookahead <= '~')) ADVANCE(10);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(3);
      if (lookahead != 0) ADVANCE(11);
      END_STATE();
    case 3:
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(4);
      END_STATE();
    case 4:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(12);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_LF);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(8);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(4);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_LF_LF);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(sym_field_name);
      if (('!' <= lookahead && lookahead <= '9') ||
          (';' <= lookahead && lookahead <= '~')) ADVANCE(10);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(aux_sym_field_value_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(11);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(aux_sym_field_value_token2);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(12);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(13);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 1},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 2},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LF] = ACTIONS(1),
    [anon_sym_LF_LF] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [sym_field_name] = ACTIONS(1),
    [aux_sym_field_value_token2] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(22),
    [sym_stanza] = STATE(13),
    [sym_field] = STATE(8),
    [anon_sym_LF] = ACTIONS(3),
    [sym_field_name] = ACTIONS(5),
    [sym_comment] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 4,
    ACTIONS(5), 1,
      sym_field_name,
    ACTIONS(11), 1,
      sym_comment,
    STATE(17), 1,
      sym_field,
    ACTIONS(9), 2,
      ts_builtin_sym_end,
      anon_sym_LF_LF,
  [14] = 4,
    ACTIONS(15), 1,
      anon_sym_LF,
    ACTIONS(17), 1,
      aux_sym_field_value_token2,
    STATE(5), 1,
      aux_sym_field_value_repeat1,
    ACTIONS(13), 2,
      ts_builtin_sym_end,
      anon_sym_LF_LF,
  [28] = 4,
    ACTIONS(5), 1,
      sym_field_name,
    ACTIONS(11), 1,
      sym_comment,
    STATE(17), 1,
      sym_field,
    ACTIONS(19), 2,
      ts_builtin_sym_end,
      anon_sym_LF_LF,
  [42] = 4,
    ACTIONS(23), 1,
      anon_sym_LF,
    ACTIONS(25), 1,
      aux_sym_field_value_token2,
    STATE(6), 1,
      aux_sym_field_value_repeat1,
    ACTIONS(21), 2,
      ts_builtin_sym_end,
      anon_sym_LF_LF,
  [56] = 4,
    ACTIONS(29), 1,
      anon_sym_LF,
    ACTIONS(31), 1,
      aux_sym_field_value_token2,
    STATE(6), 1,
      aux_sym_field_value_repeat1,
    ACTIONS(27), 2,
      ts_builtin_sym_end,
      anon_sym_LF_LF,
  [70] = 4,
    ACTIONS(5), 1,
      sym_field_name,
    ACTIONS(7), 1,
      sym_comment,
    STATE(8), 1,
      sym_field,
    STATE(14), 1,
      sym_stanza,
  [83] = 3,
    ACTIONS(36), 1,
      anon_sym_LF,
    STATE(9), 1,
      aux_sym_stanza_repeat1,
    ACTIONS(34), 2,
      ts_builtin_sym_end,
      anon_sym_LF_LF,
  [94] = 3,
    ACTIONS(38), 1,
      anon_sym_LF,
    STATE(11), 1,
      aux_sym_stanza_repeat1,
    ACTIONS(9), 2,
      ts_builtin_sym_end,
      anon_sym_LF_LF,
  [105] = 4,
    ACTIONS(5), 1,
      sym_field_name,
    ACTIONS(7), 1,
      sym_comment,
    STATE(8), 1,
      sym_field,
    STATE(21), 1,
      sym_stanza,
  [118] = 3,
    ACTIONS(42), 1,
      anon_sym_LF,
    STATE(11), 1,
      aux_sym_stanza_repeat1,
    ACTIONS(40), 2,
      ts_builtin_sym_end,
      anon_sym_LF_LF,
  [129] = 2,
    STATE(18), 1,
      sym_field_value,
    ACTIONS(45), 2,
      aux_sym_field_value_token1,
      aux_sym_field_value_token2,
  [137] = 3,
    ACTIONS(47), 1,
      ts_builtin_sym_end,
    ACTIONS(49), 1,
      anon_sym_LF_LF,
    STATE(15), 1,
      aux_sym_source_file_repeat1,
  [147] = 3,
    ACTIONS(49), 1,
      anon_sym_LF_LF,
    ACTIONS(51), 1,
      ts_builtin_sym_end,
    STATE(16), 1,
      aux_sym_source_file_repeat1,
  [157] = 3,
    ACTIONS(49), 1,
      anon_sym_LF_LF,
    ACTIONS(51), 1,
      ts_builtin_sym_end,
    STATE(19), 1,
      aux_sym_source_file_repeat1,
  [167] = 3,
    ACTIONS(49), 1,
      anon_sym_LF_LF,
    ACTIONS(53), 1,
      ts_builtin_sym_end,
    STATE(19), 1,
      aux_sym_source_file_repeat1,
  [177] = 2,
    ACTIONS(55), 1,
      anon_sym_LF,
    ACTIONS(40), 2,
      ts_builtin_sym_end,
      anon_sym_LF_LF,
  [185] = 2,
    ACTIONS(59), 1,
      anon_sym_LF,
    ACTIONS(57), 2,
      ts_builtin_sym_end,
      anon_sym_LF_LF,
  [193] = 3,
    ACTIONS(61), 1,
      ts_builtin_sym_end,
    ACTIONS(63), 1,
      anon_sym_LF_LF,
    STATE(19), 1,
      aux_sym_source_file_repeat1,
  [203] = 3,
    ACTIONS(5), 1,
      sym_field_name,
    ACTIONS(11), 1,
      sym_comment,
    STATE(17), 1,
      sym_field,
  [213] = 1,
    ACTIONS(61), 2,
      ts_builtin_sym_end,
      anon_sym_LF_LF,
  [218] = 1,
    ACTIONS(66), 1,
      ts_builtin_sym_end,
  [222] = 1,
    ACTIONS(68), 1,
      anon_sym_COLON,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 14,
  [SMALL_STATE(4)] = 28,
  [SMALL_STATE(5)] = 42,
  [SMALL_STATE(6)] = 56,
  [SMALL_STATE(7)] = 70,
  [SMALL_STATE(8)] = 83,
  [SMALL_STATE(9)] = 94,
  [SMALL_STATE(10)] = 105,
  [SMALL_STATE(11)] = 118,
  [SMALL_STATE(12)] = 129,
  [SMALL_STATE(13)] = 137,
  [SMALL_STATE(14)] = 147,
  [SMALL_STATE(15)] = 157,
  [SMALL_STATE(16)] = 167,
  [SMALL_STATE(17)] = 177,
  [SMALL_STATE(18)] = 185,
  [SMALL_STATE(19)] = 193,
  [SMALL_STATE(20)] = 203,
  [SMALL_STATE(21)] = 213,
  [SMALL_STATE(22)] = 218,
  [SMALL_STATE(23)] = 222,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_stanza, 2, 0, 0),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_value, 1, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_field_value, 1, 0, 0),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_stanza, 3, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_value, 2, 0, 0),
  [23] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_field_value, 2, 0, 0),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_field_value_repeat1, 2, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_field_value_repeat1, 2, 0, 0),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_field_value_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [34] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_stanza, 1, 0, 0),
  [36] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [38] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [40] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_stanza_repeat1, 2, 0, 0),
  [42] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_stanza_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 3, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_stanza_repeat1, 2, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field, 3, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_field, 3, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [63] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [66] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_debian(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
