/* Automatically @generated by tree-sitter v0.25.8 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 18
#define LARGE_STATE_COUNT 3
#define SYMBOL_COUNT 23
#define ALIAS_COUNT 0
#define TOKEN_COUNT 14
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 3
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 4
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LF = 1,
  anon_sym_POUND = 2,
  sym_comment_body = 3,
  anon_sym_PLUS_EQ = 4,
  anon_sym_EQ = 5,
  sym_identifier = 6,
  anon_sym_YES = 7,
  anon_sym_NO = 8,
  sym_number = 9,
  sym_quoted_string = 10,
  sym_unquoted_string = 11,
  anon_sym_BSLASH = 12,
  anon_sym_LF2 = 13,
  sym_doxyfile = 14,
  sym_comment = 15,
  sym_option = 16,
  sym_value = 17,
  sym_literal = 18,
  sym_boolean = 19,
  sym__ENL = 20,
  aux_sym_doxyfile_repeat1 = 21,
  aux_sym_value_repeat1 = 22,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LF] = "\n",
  [anon_sym_POUND] = "#",
  [sym_comment_body] = "comment_body",
  [anon_sym_PLUS_EQ] = "+=",
  [anon_sym_EQ] = "=",
  [sym_identifier] = "identifier",
  [anon_sym_YES] = "YES",
  [anon_sym_NO] = "NO",
  [sym_number] = "number",
  [sym_quoted_string] = "quoted_string",
  [sym_unquoted_string] = "unquoted_string",
  [anon_sym_BSLASH] = "\\",
  [anon_sym_LF2] = "\n",
  [sym_doxyfile] = "doxyfile",
  [sym_comment] = "comment",
  [sym_option] = "option",
  [sym_value] = "value",
  [sym_literal] = "literal",
  [sym_boolean] = "boolean",
  [sym__ENL] = "_ENL",
  [aux_sym_doxyfile_repeat1] = "doxyfile_repeat1",
  [aux_sym_value_repeat1] = "value_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LF] = anon_sym_LF,
  [anon_sym_POUND] = anon_sym_POUND,
  [sym_comment_body] = sym_comment_body,
  [anon_sym_PLUS_EQ] = anon_sym_PLUS_EQ,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_identifier] = sym_identifier,
  [anon_sym_YES] = anon_sym_YES,
  [anon_sym_NO] = anon_sym_NO,
  [sym_number] = sym_number,
  [sym_quoted_string] = sym_quoted_string,
  [sym_unquoted_string] = sym_unquoted_string,
  [anon_sym_BSLASH] = anon_sym_BSLASH,
  [anon_sym_LF2] = anon_sym_LF,
  [sym_doxyfile] = sym_doxyfile,
  [sym_comment] = sym_comment,
  [sym_option] = sym_option,
  [sym_value] = sym_value,
  [sym_literal] = sym_literal,
  [sym_boolean] = sym_boolean,
  [sym__ENL] = sym__ENL,
  [aux_sym_doxyfile_repeat1] = aux_sym_doxyfile_repeat1,
  [aux_sym_value_repeat1] = aux_sym_value_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [sym_comment_body] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_PLUS_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_YES] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_NO] = {
    .visible = true,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_string] = {
    .visible = true,
    .named = true,
  },
  [sym_unquoted_string] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_BSLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LF2] = {
    .visible = true,
    .named = false,
  },
  [sym_doxyfile] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_option] = {
    .visible = true,
    .named = true,
  },
  [sym_value] = {
    .visible = true,
    .named = true,
  },
  [sym_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [sym__ENL] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_doxyfile_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_value_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_body = 1,
  field_key = 2,
  field_value = 3,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_body] = "body",
  [field_key] = "key",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_body, 1},
  [1] =
    {field_key, 0},
  [2] =
    {field_key, 0},
    {field_value, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(9);
      ADVANCE_MAP(
        '\n', 29,
        '"', 2,
        '#', 11,
        '+', 3,
        '=', 15,
        'N', 5,
        'Y', 4,
        '\\', 28,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(7);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(21);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(10);
      if (lookahead == '"') ADVANCE(2);
      if (lookahead == 'N') ADVANCE(25);
      if (lookahead == 'Y') ADVANCE(24);
      if (lookahead == '\\') ADVANCE(28);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(22);
      if (lookahead != 0) ADVANCE(27);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(23);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '=') ADVANCE(14);
      END_STATE();
    case 4:
      if (lookahead == 'E') ADVANCE(6);
      END_STATE();
    case 5:
      if (lookahead == 'O') ADVANCE(19);
      END_STATE();
    case 6:
      if (lookahead == 'S') ADVANCE(17);
      END_STATE();
    case 7:
      if (eof) ADVANCE(9);
      ADVANCE_MAP(
        '\n', 10,
        '"', 2,
        '#', 11,
        '+', 3,
        '=', 15,
        'N', 5,
        'Y', 4,
        '\\', 28,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(7);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(21);
      END_STATE();
    case 8:
      if (eof) ADVANCE(9);
      if (lookahead == '\n') ADVANCE(10);
      if (lookahead == '#') ADVANCE(11);
      if (lookahead == '+') ADVANCE(3);
      if (lookahead == '=') ADVANCE(15);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(8);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_LF);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_comment_body);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(12);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(13);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_comment_body);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(13);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_PLUS_EQ);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_YES);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_YES);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(27);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_NO);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_NO);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(27);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(22);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(27);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_quoted_string);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_unquoted_string);
      if (lookahead == 'E') ADVANCE(26);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(27);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_unquoted_string);
      if (lookahead == 'O') ADVANCE(20);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(27);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_unquoted_string);
      if (lookahead == 'S') ADVANCE(18);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(27);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_unquoted_string);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_BSLASH);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_LF2);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 8},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 8},
  [6] = {.lex_state = 8},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 8},
  [11] = {.lex_state = 8},
  [12] = {.lex_state = 12},
  [13] = {.lex_state = 8},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 8},
  [16] = {.lex_state = 8},
  [17] = {.lex_state = 8},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LF] = ACTIONS(3),
    [anon_sym_POUND] = ACTIONS(1),
    [anon_sym_PLUS_EQ] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_YES] = ACTIONS(1),
    [anon_sym_NO] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_quoted_string] = ACTIONS(1),
    [anon_sym_BSLASH] = ACTIONS(1),
    [anon_sym_LF2] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_doxyfile] = STATE(13),
    [sym_comment] = STATE(15),
    [sym_option] = STATE(15),
    [aux_sym_doxyfile_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_LF] = ACTIONS(7),
    [anon_sym_POUND] = ACTIONS(9),
    [sym_identifier] = ACTIONS(11),
  },
  [STATE(2)] = {
    [sym_value] = STATE(17),
    [sym_literal] = STATE(3),
    [sym_boolean] = STATE(8),
    [sym__ENL] = STATE(3),
    [aux_sym_value_repeat1] = STATE(3),
    [anon_sym_LF] = ACTIONS(13),
    [anon_sym_YES] = ACTIONS(15),
    [anon_sym_NO] = ACTIONS(15),
    [sym_number] = ACTIONS(17),
    [sym_quoted_string] = ACTIONS(19),
    [sym_unquoted_string] = ACTIONS(17),
    [anon_sym_BSLASH] = ACTIONS(21),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 7,
    ACTIONS(19), 1,
      sym_quoted_string,
    ACTIONS(21), 1,
      anon_sym_BSLASH,
    ACTIONS(23), 1,
      anon_sym_LF,
    STATE(8), 1,
      sym_boolean,
    ACTIONS(15), 2,
      anon_sym_YES,
      anon_sym_NO,
    ACTIONS(17), 2,
      sym_number,
      sym_unquoted_string,
    STATE(4), 3,
      sym_literal,
      sym__ENL,
      aux_sym_value_repeat1,
  [26] = 7,
    ACTIONS(25), 1,
      anon_sym_LF,
    ACTIONS(33), 1,
      sym_quoted_string,
    ACTIONS(36), 1,
      anon_sym_BSLASH,
    STATE(8), 1,
      sym_boolean,
    ACTIONS(27), 2,
      anon_sym_YES,
      anon_sym_NO,
    ACTIONS(30), 2,
      sym_number,
      sym_unquoted_string,
    STATE(4), 3,
      sym_literal,
      sym__ENL,
      aux_sym_value_repeat1,
  [52] = 6,
    ACTIONS(7), 1,
      anon_sym_LF,
    ACTIONS(9), 1,
      anon_sym_POUND,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(39), 1,
      ts_builtin_sym_end,
    STATE(6), 1,
      aux_sym_doxyfile_repeat1,
    STATE(15), 2,
      sym_comment,
      sym_option,
  [72] = 6,
    ACTIONS(7), 1,
      anon_sym_LF,
    ACTIONS(41), 1,
      ts_builtin_sym_end,
    ACTIONS(43), 1,
      anon_sym_POUND,
    ACTIONS(46), 1,
      sym_identifier,
    STATE(6), 1,
      aux_sym_doxyfile_repeat1,
    STATE(15), 2,
      sym_comment,
      sym_option,
  [92] = 2,
    ACTIONS(49), 3,
      anon_sym_LF,
      sym_quoted_string,
      anon_sym_BSLASH,
    ACTIONS(51), 4,
      anon_sym_YES,
      anon_sym_NO,
      sym_number,
      sym_unquoted_string,
  [104] = 2,
    ACTIONS(53), 3,
      anon_sym_LF,
      sym_quoted_string,
      anon_sym_BSLASH,
    ACTIONS(55), 4,
      anon_sym_YES,
      anon_sym_NO,
      sym_number,
      sym_unquoted_string,
  [116] = 2,
    ACTIONS(57), 3,
      anon_sym_LF,
      sym_quoted_string,
      anon_sym_BSLASH,
    ACTIONS(59), 4,
      anon_sym_YES,
      anon_sym_NO,
      sym_number,
      sym_unquoted_string,
  [128] = 2,
    ACTIONS(7), 1,
      anon_sym_LF,
    ACTIONS(41), 3,
      ts_builtin_sym_end,
      anon_sym_POUND,
      sym_identifier,
  [137] = 2,
    ACTIONS(7), 1,
      anon_sym_LF,
    ACTIONS(61), 2,
      anon_sym_PLUS_EQ,
      anon_sym_EQ,
  [145] = 2,
    ACTIONS(3), 1,
      anon_sym_LF,
    ACTIONS(63), 1,
      sym_comment_body,
  [152] = 2,
    ACTIONS(7), 1,
      anon_sym_LF,
    ACTIONS(65), 1,
      ts_builtin_sym_end,
  [159] = 2,
    ACTIONS(3), 1,
      anon_sym_LF,
    ACTIONS(67), 1,
      anon_sym_LF2,
  [166] = 1,
    ACTIONS(69), 1,
      anon_sym_LF,
  [170] = 1,
    ACTIONS(71), 1,
      anon_sym_LF,
  [174] = 1,
    ACTIONS(73), 1,
      anon_sym_LF,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(3)] = 0,
  [SMALL_STATE(4)] = 26,
  [SMALL_STATE(5)] = 52,
  [SMALL_STATE(6)] = 72,
  [SMALL_STATE(7)] = 92,
  [SMALL_STATE(8)] = 104,
  [SMALL_STATE(9)] = 116,
  [SMALL_STATE(10)] = 128,
  [SMALL_STATE(11)] = 137,
  [SMALL_STATE(12)] = 145,
  [SMALL_STATE(13)] = 152,
  [SMALL_STATE(14)] = 159,
  [SMALL_STATE(15)] = 166,
  [SMALL_STATE(16)] = 170,
  [SMALL_STATE(17)] = 174,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_doxyfile, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_option, 2, 0, 2),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_value, 1, 0, 0),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_value_repeat1, 2, 0, 0),
  [27] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_value_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [30] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_value_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_value_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [36] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_value_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_doxyfile, 1, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_doxyfile_repeat1, 2, 0, 0),
  [43] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_doxyfile_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [46] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_doxyfile_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean, 1, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_literal, 1, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_literal, 1, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__ENL, 2, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__ENL, 2, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [65] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2, 0, 1),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_option, 3, 0, 3),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_doxyfile(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
